[package]
authors = ["Trenton Andres <trenton.andres@gmail.com>"]
name = "client"
version = "0.1.0"
edition = "2018"

[dependencies]
libusb = "0.3.0"
tokio = { version = "1.8.1", features = ["macros", "time", "rt", "sync"] }
common = { path="../common" }
thiserror = "1.0.26"
