[package]
name = "common"
version = "0.1.0"
edition = "2018"

[dependencies]
cobs = { version = "0.1.4", default-features = false }
embedded-hal = "0.2"
nb = "1.0.0"
usb-device = "0.2.8"
ringbuffer = { version = "0.7.1", default-features = false }
serde = { version = "1.0.126", features = ["derive"], default-features = false }
serde-big-array = "0.3.2"
serde_cbor = {version = "0.11", default-features = false }

[features]
default = ["std"]
std = ["serde/std", "serde_cbor/std"]
