# Assuming discovery target board here
[target.thumbv7em-none-eabihf]
runner = "gdb-multiarch -q -x openocd.gdb"

rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7em-none-eabihf"
